<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Easy\**" />
    <Compile Remove="Hard\**" />
    <Compile Remove="Medium\**" />
    <EmbeddedResource Remove="Easy\**" />
    <EmbeddedResource Remove="Hard\**" />
    <EmbeddedResource Remove="Medium\**" />
    <None Remove="Easy\**" />
    <None Remove="Hard\**" />
    <None Remove="Medium\**" />
  </ItemGroup>

</Project>
